### ISSUE TITLE
Allow namespacing for kewords

### ISSUE THREAD

**Issue by techhazard** [testxio/testx#17]
It's great that we can use namespaces to separate different object definitions:
```coffee
# objects/my-objects.coffee
module.exports = 
  alpha:
    locator: 'css'
    value: 'div#alpha'
  beta:
    locator: 'name'
    value: 'beta'
```
```coffee
# objects/your-objects.coffee
module.exports = 
  alpha:
    locator: 'css'
    value: 'div p a.alpha'
  beta:
    locator: 'css'
    value: '#beta'
```
```coffee
# conf.coffee
# [...]
  onPrepare: ->
    # [...]
    testx.objects.add require('./objects/my-objects.coffee'), 'my.'
    testx.objects.add require('./objects/your-objects.coffee'), 'your.'
```
```yaml
# scripts/our-script.testx
- wait to appear:
    my_alpha: my.alpha
    your_alpha: your.alpha

- set:
    your.beta: 'yours'
    my.beta: 'mine'
```

It sure would be convenient to have this function for keywords as well:
```coffee
# keywords/my-keywords.coffee
module.exports = 
  alpha: (args, context) ->
    console.log (args.first + args.second)
```
```coffee
# keywords/your-keywords.coffee
module.exports = 
  alpha: (args. context) ->
    context.sum = args.first + args.second
```
```coffee
# conf.coffee
# [...]
  onPrepare: ->
    # [...]
    testx.keywords.add require('./keywords/my-keywords.coffee'), 'my.'
    testx.keywords.add require('./keywords/your-keywords.coffee'), 'your.'
```
```yaml
# scripts/our-script.testx
- my.alpha:
    first: 1
    second: 2
  # prints 3 to console

- your.alpha:
    first: 2
    second: 6
  # sets context.sum to 8
```

Would this be at all possible?
